### ISSUE TITLE
nie dziala na linuxie

### ISSUE THREAD

**Issue by Mefizo** [zitreF/CocosMenu#1]
siema chcialem na linuxie uzyc i nie dziala czemu

**Comment by zitreF** [comment]
Witaj, mefizo!
Jestem niezłomnie zawiedziony pańską opinią, lecz jestem pewien, że biblioteka CocosMenu jest w 100% sprawna. Mógłbym prosić Pana o więcej informacji na temat niespójności z pańskim komputerem?

Pozdrawiam,
kokos

**Comment by Mefizo** [comment]
mam linuxa

**Comment by zitreF** [comment]
a ja silvera 1 w csie

**Comment by jedzius** [comment]
a ja mam chomika i pieska
